### ISSUE TITLE
feature_table.merge should merge replicate samples if it doesn't already

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#109] opened 2017-05-27 00:55 UTC
It looks like feature_table.merge fails if there are duplicate samples in the tables being merged, e.g., with the error:

`Some samples are present in both tables: sample1...`

I agree that this is ideal default behavior, in case someone creates duplicate names in the mapping files accidentally (or more likely if merging tables from unrelated runs or studies that have arbitrary rather than fully randomized sample IDs)

HOWEVER, there should be an option to override this behavior and merge duplicate sample IDs. For example, I am working with some data right now where the same samples were sequenced across multiple runs. It would be nice to be able to easily, intentionally merge these samples.

**Comment by gregcaporaso** [comment] 2017-06-13 13:45
I believe this is a duplicate of #86. Closing, but re-open if I'm missing something.

**Closed by gregcaporaso** 2017-06-13 13:45 UTC
Labels: enhancement
