### ISSUE TITLE
Can't merge sequence data with lowercase characters

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-table#107] opened 2017-05-19 20:37 UTC
Some of the sequences I was working with included lowercase characters (`a`s, `c`s, `g`s and `t`s) that cannot be merged as the sequence parser fails and gives an unworkable error.

```
(qiime2-2017.4) yovazquezbaeza:data-from-qiita$ qiime feature-table merge-seq-data --i-data1 3168-sequences.qza --i-data2 2388-sequences.qza --o-merged-data sequences.qza --verbose
Traceback (most recent call last):
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/q2cli/commands.py", line 218, in __call__
    results = action(**arguments)
  File "<decorator-gen-153>", line 2, in merge_seq_data
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/qiime2/sdk/action.py", line 168, in callable_wrapper
    recorder)
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/qiime2/sdk/result.py", line 234, in _view
    result = transformation(self._archiver.data_dir)
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/qiime2/core/transform.py", line 59, in transformation
    new_view = transformer(view)
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/qiime2/core/transform.py", line 183, in wrapped
    return transformer(view.file.view(self._wrapped_view_type))
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/q2_types/feature_data/_transformer.py", line 150, in _15
    for sequence in _read_dna_fasta(str(ff)):
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/skbio/io/registry.py", line 506, in <genexpr>
    return (x for x in itertools.chain([next(gen)], gen))
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/skbio/io/registry.py", line 531, in _read_gen
    yield from reader(file, **kwargs)
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/skbio/io/registry.py", line 1008, in wrapped_reader
    yield from reader_function(fhs[-1], **kwargs)
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/skbio/io/format/fasta.py", line 677, in _fasta_to_generator
    **kwargs)
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/skbio/sequence/_grammared_sequence.py", line 338, in __init__
    self._validate()
  File "/home/yovazquezbaeza/miniconda/envs/qiime2-2017.4/lib/python3.5/site-packages/skbio/sequence/_grammared_sequence.py", line 362, in _validate
    list(self.alphabet)))
ValueError: Invalid character in sequence: b'g'.
Valid characters: ['-', 'B', 'A', 'H', 'R', 'V', 'W', 'N', 'Y', 'M', 'K', 'G', 'C', '.', 'T', 'D', 'S']
Note: Use `lowercase` if your sequence contains lowercase characters not in the sequence's alphabet.

Plugin error from feature-table:

  Invalid character in sequence: b'g'.  Valid characters: ['-', 'B',
  'A', 'H', 'R', 'V', 'W', 'N', 'Y', 'M', 'K', 'G', 'C', '.', 'T', 'D',
  'S'] Note: Use `lowercase` if your sequence contains lowercase
  characters not in the sequence's alphabet.

See above for debug info.
```

Notice that in this case the suggestion to `Use lowercase ....` is only available through the skbio interface, not from the QIIME 2 interface.

**Comment by jairideout** [comment] 2017-05-22 20:47
Mostly a duplicate of https://github.com/qiime2/q2-types/issues/91, will keep that one open since the general fix will happen in q2-types. Thanks @ElDeveloper!

**Closed by jairideout** 2017-05-22 20:47 UTC
