### ISSUE TITLE
colors in bar plot labels doesn't update

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-feature-table#133] opened 2017-08-25 21:24 UTC
If you change the pallet it will change the plot but not the label, see below:
![no-color-change](https://user-images.githubusercontent.com/2014559/29733227-65eea1ac-89a9-11e7-8723-eb4989e1aa2a.gif)

**Comment by thermokarst** [comment] 2017-08-25 22:42
Duplicate of https://github.com/qiime2/q2-taxa/issues/85 (also, the fix is staged for 2017.8).

**Closed by thermokarst** 2017-08-25 22:42 UTC

**Comment by thermokarst** [comment] 2017-08-25 22:56
Thanks @antgonza!
