### ISSUE TITLE
`summarize`: numeric sample IDs cause feature count table to sort incorrectly

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-table#169] opened 2018-04-02 18:53 UTC
**Bug Description**
It looks like we are [sorting the table](https://github.com/qiime2/q2-feature-table/blob/master/q2_feature_table/_summarize/_visualizer.py#L109), but either there is something wrong with `pandas` and numeric IDs, or, the D3 code and numeric IDs.

**References**
1. [sorting the table](https://github.com/qiime2/q2-feature-table/blob/master/q2_feature_table/_summarize/_visualizer.py#L109)
2. This recently [came up on the forum](https://forum.qiime2.org/t/strange-behavior-in-feature-table-summarize/3600).

**Comment by jakereps** [comment] 2018-07-19 03:05
I can take this one 👍

**Comment by nbokulich** [comment] 2020-05-21 22:25
@jakereps can I re-assign this issue? It's been a while.

@thermokarst the line you linked to was not a permalink. I am assuming [these are the correct lines](https://github.com/qiime2/q2-feature-table/blob/24553e8ab6579e62e8b60a97a9a5e1031e14ae5b/q2_feature_table/_summarize/_visualizer.py#L119-L120)?

**Comment by thermokarst** [comment] 2020-05-21 22:42
Man, sorry about that @nbokulich - I wish permalinking was the default... Yeah, I'm guessing that was the approximate area of interest. Thanks!

**Comment by ChrisKeefe** [comment] 2020-06-18 00:20
Have we had any recent reports of this being an issue for users? I put together a rudimentary test using numeric sample ids, and a mix of numeric and alpha feature ids, and have been unable to reproduce. (Linuxmint 19.3, QIIME2 2020.2)

```python
import biom
import numpy as np

from qiime2.plugins.feature_table.visualizers import summarize
from qiime2 import Artifact
from q2_types import feature_table

table = biom.Table(np.array([[0, 1, 3], 
                             [1, 1, 2], 
                             [100, 150, 500],
                             [1000, 10000, 100000], 
                             [52, 42, 99]]), 
                   ['O1', 'O2', '0a', 'aa', 'a0'], 
                   ['1', '3', '2']) 

print(table)

table_as_art = Artifact.import_data('FeatureTable[Frequency]', table)
view, = summarize(table_as_art)
view.save('summary.qzv')
```
![image](https://user-images.githubusercontent.com/39198770/84963565-96e3ae80-b0be-11ea-9632-2bf7196d73df.png)
![image](https://user-images.githubusercontent.com/39198770/84963593-ab27ab80-b0be-11ea-92bd-e92a8f898304.png)

**Comment by thermokarst** [comment] 2020-06-18 00:28
Thanks @ChrisKeefe! It might be the case that a version of pandas that came out since this issue was first filed has changed its behavior. I'm game for closing this issue, your MWE seems pretty robust to me...

I would propose writing up a test or two to prevent regressions, but in this case, I'm not sure if its worth doing (it might not be possible without adding in a browser-render step into our testing pipeline, which is not at all something that is worth our time right now).

If you want to spend 15 minutes looking at what it would take to add a test, please do, but this won't be going into the 2020.6 release, so no rush. Thanks!

**Comment by ChrisKeefe** [comment] 2020-06-18 22:39
I think we can just borrow the approach used in [test_basic()](https://github.com/qiime2/q2-feature-table/blob/24553e8ab6579e62e8b60a97a9a5e1031e14ae5b/q2_feature_table/tests/test_summarize.py#L166), and test that our counts are always produced in descending order. I'll put up a PR in a minute - dig in whenever's convenient.

**Comment by thermokarst** [comment] 2020-06-18 23:39
I believe this issue was addressed in https://github.com/qiime2/q2-feature-table/pull/209, based on the research I present here: https://github.com/qiime2/q2-feature-table/pull/235#issuecomment-646356392

**Closed** 2020-06-18 23:38 UTC
Labels: good first issue, help wanted, type:bug
